spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
